### ISSUE TITLE
Release new package to npm

### ISSUE THREAD

**Issue by ctavan** [patrickml/react-flexbox-grid-aphrodite#3]
Thank you for merging #2 so quickly. Would you mind publishing a new package to npm? Thanks!

**Comment by patrickml** [comment]
@ctavan i'm having issues with my personal computer and cannot do this from my work computer. I'll try from a friends later today.

**Comment by patrickml** [comment]
@ctavan it should be up to date https://www.npmjs.com/package/react-flexbox-grid-aphrodite
