### ISSUE TITLE
How to override the width of grid?

### ISSUE THREAD

**Issue by HaciKale** [patrickml/react-flexbox-grid-aphrodite#4]
Is there anyway to override the width to fill the screen 100%?

**Comment by patrickml** [comment]
@HaciKale are you looking for container-fluid?

**Comment by patrickml** [comment]
https://github.com/patrickml/react-flexbox-grid-aphrodite/blob/master/src/components/grid.js#L9

**Comment by HaciKale** [comment]
Sorry I couldn't make it work at all, so I skipped it and am just using the usual "col-xs-12" class etc
